# Generated by Django 2.1.15 on 2020-10-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('nur_hosp_yn', models.IntegerField()),
                ('ac_ctr_diff', models.IntegerField()),
                ('hsp_avg_optt_bilg_isamt_s', models.FloatField()),
                ('hsp_avg_surop_bilg_isamt_s', models.FloatField()),
                ('ar_rclss_cd', models.IntegerField()),
                ('fds_cust_yn', models.IntegerField()),
                ('hspz_dys_s', models.FloatField()),
                ('inamt_nvcd', models.IntegerField()),
                ('hsp_avg_diag_bilg_isamt_s', models.FloatField()),
                ('blrs_cd', models.IntegerField()),
                ('dsas_ltwt_gcd', models.IntegerField()),
                ('dsas_avg_diag_bilg_isamt_s', models.FloatField()),
                ('dsas_acd_rst_dcd', models.IntegerField()),
                ('base_ym', models.IntegerField()),
                ('kcd_gcd', models.IntegerField()),
                ('hsp_avg_hspz_bilg_isamt_s', models.FloatField()),
                ('optt_blcnt_s', models.FloatField()),
                ('mtad_cntr_yn', models.IntegerField()),
                ('heltp_pf_ntyn', models.IntegerField()),
                ('prm_nvcd', models.IntegerField()),
                ('surop_blcnt_s', models.FloatField()),
                ('mdct_inu_rclss_dcd', models.IntegerField()),
                ('dsas_avg_optt_bilg_isamt_s', models.FloatField()),
                ('isrd_age_dcd', models.IntegerField()),
                ('hspz_blcnt_s', models.FloatField()),
                ('dsas_avg_surop_bilg_isamt_s', models.FloatField()),
                ('urlb_fc_yn', models.IntegerField()),
                ('dsas_avg_hspz_bilg_isamt_s', models.FloatField()),
                ('smrtg_5y_passed_yn', models.IntegerField()),
                ('ac_rst_diff', models.IntegerField()),
                ('bilg_isamt_s', models.FloatField()),
                ('optt_nbtm_s', models.FloatField()),
                ('자동지급', models.FloatField(null=True)),
                ('심사', models.FloatField(null=True)),
                ('조사', models.FloatField(null=True)),
                ('target', models.CharField(max_length=15, null=True)),
            ],
            options={
                'ordering': ('-ID',),
            },
        ),
        migrations.CreateModel(
            name='LimeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('feature', models.CharField(max_length=50)),
                ('local_exp', models.FloatField()),
                ('discretized', models.TextField(max_length=100, null=True)),
                ('value', models.FloatField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='app.InsuranceClaim')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='limereport',
            unique_together={('claim', 'rank')},
        ),
    ]
